/**
 * Brand-owned settings (name, package, icons, splash) come from brand/brand.json;
 * everything else stays in app.json. Icons are generated by `pnpm brand`.
 *
 * Changing ids.androidPackage after tablets are in use makes the new APK a
 * different app: it installs beside the old one, unpaired, with an empty queue.
 */
const brand = require('../../brand/brand.json')

module.exports = ({ config }) => ({
  ...config,
  name: brand.productName,
  icon: './assets/icon.png',
  android: {
    ...config.android,
    package: brand.ids.androidPackage,
    adaptiveIcon: {
      foregroundImage: './assets/adaptive-icon.png',
      monochromeImage: './assets/monochrome-icon.png',
      backgroundColor: brand.colors.primary,
    },
  },
  plugins: [
    ...config.plugins,
    ['expo-splash-screen', {
      image: './assets/splash-icon.png',
      imageWidth: 160,
      backgroundColor: brand.colors.splashBackground,
    }],
  ],
})
