/**
 * Public half of the vendor's licence signing key (Ed25519).
 *
 * Safe to commit — it can only VERIFY licences. The private half lives in
 * ~/.almanzil-pos/licence-private.pem on the vendor's machine and must never
 * enter this repository. Generated by `node tools/licence.mjs keygen`.
 *
 * Rotating it invalidates every licence already issued.
 */
export const LICENCE_PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAWOD39VGlF4CRYQjCt4XI1cKc2P5U0PLwWGmIsYWIuWI=
-----END PUBLIC KEY-----
`
